version: '2.4'
services:
  postgres:
    container_name: pgsql
    image: skyrabot/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'changemepls'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  lavalink:
    container_name: lavalink
    image: skyrabot/lavalink:main
    restart: always
    ports:
      - '2333:2333'
  influx:
    container_name: influxdb
    image: quay.io/influxdb/influxdb:2.0.0-beta
    restart: always
    volumes:
      - influx-data:/var/lib/influxdb2
    ports:
      - '8285:9999'
    command: influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store bolt

volumes:
  postgres-data:
    external: true
  influx-data:
    external: true
