import type { Song } from '@lib/structures/music/Song';
import type { ScheduleEntity } from '@orm/entities/ScheduleEntity';
import type { StatsGeneral, StatsUptime, StatsUsage } from '@root/commands/System/stats';
import type { Moderation } from '@utils/constants';
import type { LanguageHelpDisplayOptions } from '@utils/LanguageHelp';
import type { Guild, GuildMember, Role, User } from 'discord.js';

export interface ModerationAction {
	addRole: string;
	mute: string;
	ban: string;
	kick: string;
	softban: string;
	vkick: string;
	vmute: string;
	restrictedReact: string;
	restrictedEmbed: string;
	restrictedAttachment: string;
	restrictedVoice: string;
	setNickname: string;
	removeRole: string;
}

declare module 'klasa' {
	export interface LanguageKeys {
		default: (params: { key: string }) => string;
		defaultLanguage: string;

		globalYes: string;
		globalNo: string;
		globalNone: string;
		globalIs: string;
		globalAnd: string;
		globalOr: string;
		globalUnknown: string;

		settingGatewayKeyNoext: (params: { key: string }) => string;
		settingGatewayChooseKey: (params: { keys: string }) => string;
		settingGatewayUnconfigurableFolder: string;
		settingGatewayUnconfigurableKey: (params: { key: string }) => string;
		settingGatewayMissingValue: (params: { path: string; value: string }) => string;
		settingGatewayDuplicateValue: (params: { path: string; value: string }) => string;
		settingGatewayInvalidFilteredValue: (params: { path: string; value: unknown }) => string;
		resolverMultiTooFew: (params: { name: string; min?: number; conjunctionWord: string }) => string;
		resolverInvalidBool: (params: { name: string }) => string;
		resolverInvalidChannel: (params: { name: string }) => string;
		resolverInvalidCustom: (params: { name: string; type: string }) => string;
		resolverInvalidDate: (params: { name: string }) => string;
		resolverInvalidDuration: (params: { name: string }) => string;
		resolverInvalidEmoji: (params: { name: string }) => string;
		resolverInvalidFloat: (params: { name: string }) => string;
		resolverInvalidGuild: (params: { name: string }) => string;
		resolverInvalidInt: (params: { name: string }) => string;
		resolverInvalidInvite: (params: { name: string }) => string;
		resolverInvalidLiteral: (params: { name: string }) => string;
		resolverInvalidMember: (params: { name: string }) => string;
		resolverInvalidMessage: (params: { name: string }) => string;
		resolverInvalidPiece: (params: { name: string; piece: string }) => string;
		resolverInvalidRegexMatch: (params: { name: string; pattern: string }) => string;
		resolverInvalidRole: (params: { name: string }) => string;
		resolverInvalidString: (params: { name: string }) => string;
		resolverInvalidTime: (params: { name: string }) => string;
		resolverInvalidUrl: (params: { name: string }) => string;
		resolverInvalidUser: (params: { name: string }) => string;
		resolverInvalidSnowflake: (params: { name: string }) => string;
		resolverInvalidStore: (params: { store: string }) => string;
		resolverStringSuffix: string;
		resolverMinmaxExactlyInclusive: (params: { name: string; min: number }) => string;
		resolverMinmaxExactlyExclusive: (params: { name: string; min: number }) => string;
		resolverMinmaxBothInclusive: (params: { name: string; min: number; max: number }) => string;
		resolverMinmaxBothExclusive: (params: { name: string; min: number; max: number }) => string;
		resolverMinmaxMinInclusive: (params: { name: string; min: number }) => string;
		resolverMinmaxMinExclusive: (params: { name: string; min: number }) => string;
		resolverMinmaxMaxInclusive: (params: { name: string; max: number }) => string;
		resolverMinmaxMaxExclusive: (params: { name: string; max: number }) => string;
		reactionhandlerPrompt: string;
		commandmessageMissing: string;
		commandmessageMissingRequired: (params: { name: string }) => string;
		commandmessageMissingOptionals: (params: { possibles: string }) => string;
		commandmessageNomatch: (params: { possibles: string }) => string;
		monitorCommandHandlerReprompt: (params: { tag: string; name: string; time: string; cancelOptions: string }) => string;
		monitorCommandHandlerRepeatingReprompt: (params: { tag: string; name: string; time: string; cancelOptions: string }) => string;
		monitorCommandHandlerAborted: string;
		inhibitorCooldown: (params: { remaining: string }) => string;
		inhibitorMissingBotPerms: (params: { missing: string }) => string;
		inhibitorNsfw: string;
		inhibitorPermissions: string;
		inhibitorRequiredSettings: (params: { settings: string; count: number }) => string;
		inhibitorRequiredSettingsPlural: (params: { settings: string; count: number }) => string;
		inhibitorRunin: (params: { type: string }) => string;
		inhibitorRuninNone: (params: { name: string }) => string;
		inhibitorDisabledGuild: string;
		inhibitorDisabledGlobal: string;
		/** used to build a LanguageBuilder for extendedHelp */
		systemHelpTitles: {
			explainedUsage: string;
			possibleFormats: string;
			examples: string;
			reminders: string;
		};
		commandBlocklistDescription: string;
		commandBlocklistSaveSuccess: string;
		commandBlocklistResetSuccess: string;
		commandUnload: (params: { type: string; name: string }) => string;
		commandUnloadDescription: string;
		commandTransferError: string;
		commandTransferSuccess: (params: { type: string; name: string }) => string;
		commandTransferFailed: (params: { type: string; name: string }) => string;
		commandTransferDescription: string;
		commandReload: (params: { type: string; name: string; time: string }) => string;
		commandReloadAll: (params: { type: string; time: string }) => string;
		commandReloadEverything: (params: { time: string }) => string;
		commandReloadFailed: (params: { type: string; name: string }) => string;
		commandReloadDescription: string;
		commandReboot: string;
		commandRebootDescription: string;
		commandPing: string;
		commandPingDescription: string;
		commandPingPong: (params: { diff: number; ping: number }) => string;
		commandInfoDescription: string;
		commandHelpDescription: string;
		commandHelpNoExtended: string;
		commandHelpDm: string;
		commandHelpNodm: string;
		commandHelpAllFlag: (params: { prefix: string }) => string;
		commandHelpCommandCount: (params: { count: number }) => string;
		commandHelpCommandCountPlural: (params: { count: number }) => string;
		commandEnable: (params: { type: string; name: string }) => string;
		commandEnableDescription: string;
		commandDisable: (params: { type: string; name: string }) => string;
		commandDisableDescription: string;
		commandDisableWarn: string;
		commandConfNoKey: string;
		commandConfNoValue: string;
		commandConfGuarded: (params: { name: string }) => string;
		commandConfUpdated: (params: { key: string; response: string }) => string;
		commandConfKeyNotArray: string;
		commandConfGetNoExt: (params: { key: string }) => string;
		commandConfGet: (params: { key: string; value: string }) => string;
		commandConfReset: (params: { key: string; value: string }) => string;
		commandConfNochange: (params: { key: string }) => string;
		commandConfServerDescription: string;
		commandConfServer: (params: { key: string; list: string }) => string;
		commandConfUserDescription: string;
		commandConfUser: (params: { key: string; list: string }) => string;
		commandConfSettingNotSet: string;
		messagePromptTimeout: string;
		textPromptAbortOptions: readonly string[];
		commandLoad: (params: { time: string; type: string; name: string }) => string;
		commandLoadFail: string;
		commandLoadError: (params: { type: string; name: string; error: string }) => string;
		commandLoadDescription: string;
		argumentRangeInvalid: (params: { name: string }) => string;
		argumentRangeMax: (params: { name: string; maximum: number; count: number }) => string;
		argumentRangeMaxPlural: (params: { name: string; maximum: number; count: number }) => string;
		commandAddDescription: string;
		commandAddExtended: LanguageHelpDisplayOptions;
		commandAddPlaylist: (params: { songs: string }) => string;
		commandAddPlaylistSongs: (params: { count: number }) => string;
		commandAddPlaylistSongsPlural: (params: { count: number }) => string;
		commandAddSong: (params: { title: string }) => string;
		commandClearDescription: string;
		commandClearDenied: string;
		commandClearSuccess: (params: { count: number }) => string;
		commandClearSuccessPlural: (params: { count: number }) => string;
		commandExportQueueDescription: string;
		commandExportQueueExtended: LanguageHelpDisplayOptions;
		commandExportQueueSuccess: (params: { guildName: string }) => string;
		commandImportQueueDescription: string;
		commandImportQueueExtended: LanguageHelpDisplayOptions;
		commandJoinDescription: string;
		commandJoinNoMember: string;
		commandJoinNoVoicechannel: string;
		commandJoinSuccess: (params: { channel: string }) => string;
		commandJoinVoiceDifferent: string;
		commandJoinVoiceFull: string;
		commandJoinVoiceNoConnect: string;
		commandJoinVoiceNoSpeak: string;
		commandJoinVoiceSame: string;
		commandJoinFailed: string;
		commandLeaveDescription: string;
		commandLeaveExtended: LanguageHelpDisplayOptions;
		commandLeaveSuccess: (params: { channel: string }) => string;
		commandPauseDescription: string;
		commandPauseSuccess: string;
		commandPlayDescription: string;
		commandPlayExtended: LanguageHelpDisplayOptions;
		commandPlayEnd: string;
		commandPlayNext: (params: { title: string; requester: string }) => string;
		commandPlayQueuePaused: (params: { song: string }) => string;
		commandPlayQueuePlaying: string;
		commandPlayQueueEmpty: string;
		commandPlayingDescription: string;
		commandPlayingDuration: (params: { duration: string }) => string;
		commandPlayingQueueEmpty: string;
		commandPlayingQueueNotPlaying: string;
		commandRepeatDescription: string;
		commandRepeatSuccessEnabled: string;
		commandRepeatSuccessDisabled: string;
		commandQueueDescription: string;
		commandQueueLast: string;
		commandQueueTitle: (params: { guildname: string }) => string;
		commandQueueLine: (params: { position: number; duration: string; title: string; url: string; requester: string }) => string;
		commandQueueNowplaying: (context: { title: string; url: string; requester: string }) => string;
		commandQueueNowplayingTimeRemaining: (params: { timeRemaining: string }) => string;
		commandQueueNowplayingLiveStream: string;
		commandQueueNowplayingTitle: string;
		commandQueueTotalTitle: string;
		commandQueueTotal: (params: { songs: string; remainingTime: string }) => string;
		commandQueueEmpty: string;
		commandQueueDashboardInfo: (params: { guild: Guild }) => string;
		commandRemoveDescription: string;
		commandRemoveIndexInvalid: string;
		commandRemoveIndexOut: (params: { songs: string }) => string;
		commandRemoveDenied: string;
		commandRemoveSuccess: (params: { song: Song }) => string;
		commandSeekDescription: string;
		commandSeekSuccess: (params: { time: number }) => string;
		commandResumeDescription: string;
		commandResumeSuccess: string;
		commandRolesetDescription: string;
		commandRolesetExtended: LanguageHelpDisplayOptions;
		commandRolesetCreated: (params: { name: string; roles: string }) => string;
		commandRolesetAdded: (params: { name: string; roles: string }) => string;
		commandRolesetInvalidName: (params: { name: string }) => string;
		commandRolesetRemoved: (params: { name: string; roles: string }) => string;
		commandRolesetResetEmpty: string;
		commandRolesetResetAll: string;
		commandRolesetResetNotExists: (params: { name: string }) => string;
		commandRolesetResetGroup: (params: { name: string }) => string;
		commandRolesetUpdated: (params: { name: string }) => string;
		commandRolesetNoRolesets: string;
		commandShuffleDescription: string;
		commandShuffleSuccess: (params: { amount: number }) => string;
		commandSkipDescription: string;
		commandSkipPermissions: string;
		commandSkipVotesVoted: string;
		commandSkipVotesTotal: (params: { amount: number; needed: number }) => string;
		commandSkipSuccess: (params: { title: string }) => string;
		commandPlayingTimeDescription: string;
		commandPlayingTimeQueueEmpty: string;
		commandPromoteDescription: string;
		commandPromoteExtended: LanguageHelpDisplayOptions;
		commandPromoteSuccess: (params: { song: Song }) => string;
		commandVolumeDescription: string;
		commandVolumeSuccess: (params: { volume: number }) => string;
		commandVolumeChanged: (params: { emoji: string; volume: number }) => string;
		commandVolumeChangedExtreme: (params: { emoji: string; text: string; volume: number }) => string;
		commandVolumeChangedTexts: readonly string[];
		commandAbilityDescription: string;
		commandAbilityExtended: LanguageHelpDisplayOptions;
		commandAbilityEmbedTitle: string;
		commandAbilityQueryFail: (params: { ability: string }) => string;
		commandFlavorsDescription: string;
		commandFlavorsExtended: LanguageHelpDisplayOptions;
		commandFlavorsQueryFail: (params: { pokemon: string }) => string;
		commandItemDescription: string;
		commandItemExtended: LanguageHelpDisplayOptions;
		commandItemEmebedData: (params: {
			availableInGen8: string;
		}) => {
			ITEM: string;
			generationIntroduced: string;
			availableInGeneration8Title: string;
			availableInGeneration8Data: string;
		};
		commandItemQueryFail: (params: { item: string }) => string;
		commandLearnDescription: string;
		commandLearnExtended: LanguageHelpDisplayOptions;
		commandLearnMethodTypes: (params: {
			level?: number | null;
		}) => {
			levelUpMoves: string;
			eventMoves: string;
			tutorMoves: string;
			eggMoves: string;
			virtualTransferMoves: string;
			tmMoves: string;
			dreamworldMoves: string;
		};
		commandLearnInvalidGeneration: (params: { generation: string }) => string;
		commandLearnMethod: (params: { generation: number; pokemon: string; move: string; method: string }) => string;
		commandLearnQueryFailed: (params: { pokemon: string; moves: string }) => string;
		commandLearnCannotLearn: (params: { pokemon: string; moves: string }) => string;
		commandLearnTitle: (params: { pokemon: string; generation: number }) => string;
		commandMoveDescription: string;
		commandMoveExtended: LanguageHelpDisplayOptions;
		commandMoveEmbedData: (params: {
			availableInGen8: string;
		}) => {
			move: string;
			types: string;
			basePower: string;
			pp: string;
			category: string;
			accuracy: string;
			priority: string;
			target: string;
			contestCondition: string;
			zCrystal: string;
			gmaxPokemon: string;
			availableInGeneration8Title: string;
			availableInGeneration8Data: string;
			none: string;
			maxMovePower: string;
			zMovePower: string;
		};
		commandMoveQueryFail: (params: { move: string }) => string;
		commandPokedexDescription: string;
		commandPokedexExtended: LanguageHelpDisplayOptions;
		commandPokedexEmbedData: (params: {
			otherFormes: readonly string[];
			cosmeticFormes: readonly string[];
		}) => {
			types: string;
			abilities: string;
			genderRatio: string;
			smogonTier: string;
			uknownSmogonTier: string;
			height: string;
			weight: string;
			eggGroups: string;
			evolutionaryLine: string;
			baseStats: string;
			baseStatsTotal: string;
			flavourText: string;
			otherFormesTitle: string;
			cosmeticFormesTitle: string;
			otherFormesList: string;
			cosmeticFormesList: string;
		};
		commandPokedexQueryFail: (params: { pokemon: string }) => string;
		commandTypeDescription: string;
		commandTypeExtended: LanguageHelpDisplayOptions;
		commandTypeEmbedData: (params: {
			types: string[];
		}) => {
			offensive: string;
			defensive: string;
			superEffectiveAgainst: string;
			dealsNormalDamageTo: string;
			doesNotAffect: string;
			notVeryEffectiveAgainst: string;
			vulnerableTo: string;
			takesNormalDamageFrom: string;
			resists: string;
			notAffectedBy: string;
			typeEffectivenessFor: string;
		};
		commandTypeTooManyTypes: string;
		commandTypeNotAType: (params: { type: string }) => string;
		commandTypeQueryFail: (params: { types: string }) => string;
		inhibitorMusicQueueEmpty: string;
		inhibitorMusicNotPlaying: string;
		inhibitorMusicPaused: string;
		inhibitorMusicDjMember: string;
		inhibitorMusicUserVoiceChannel: string;
		inhibitorMusicBotVoiceChannel: string;
		inhibitorMusicBothVoiceChannel: string;
		inhibitorMusicNothingPlaying: string;
		musicManagerFetchNoArguments: string;
		musicManagerFetchNoMatches: string;
		musicManagerFetchLoadFailed: string;
		musicManagerImportQueueNotFound: string;
		musicManagerImportQueueError: string;
		musicManagerTooManySongs: string;
		musicManagerSetvolumeSilent: string;
		musicManagerSetvolumeLoud: string;
		musicManagerPlayNoSongs: string;
		musicManagerPlayPlaying: string;
		musicManagerStuck: (params: { milliseconds: number }) => string;
		commandConfMenuNopermissions: string;
		commandConfMenuRenderAtFolder: (params: { path: string }) => string;
		commandConfMenuRenderAtPiece: (params: { path: string }) => string;
		commandConfMenuRenderNokeys: string;
		commandConfMenuRenderSelect: string;
		commandConfMenuRenderTctitle: string;
		commandConfMenuRenderUpdate: string;
		commandConfMenuRenderRemove: string;
		commandConfMenuRenderReset: string;
		commandConfMenuRenderUndo: string;
		commandConfMenuRenderCvalue: (params: { value: string }) => string;
		commandConfMenuRenderBack: string;
		commandConfMenuInvalidKey: string;
		commandConfMenuInvalidAction: string;
		commandConfMenuSaved: string;
		settingsPrefix: string;
		settingsLanguage: string;
		settingsDisabledcommands: string;
		settingsDisablenaturalprefix: string;
		settingsChannelsAnnouncements: string;
		settingsChannelsFarewell: string;
		settingsChannelsGreeting: string;
		settingsChannelsImageLogs: string;
		settingsChannelsMemberLogs: string;
		settingsChannelsMessageLogs: string;
		settingsChannelsModerationLogs: string;
		settingsChannelsNsfwMessageLogs: string;
		settingsChannelsPruneLogs: string;
		settingsChannelsReactionLogs: string;
		settingsChannelsRoles: string;
		settingsChannelsSpam: string;
		settingsChannelsIgnoreMessageDelete: string;
		settingsChannelsIgnoreMessageEdit: string;
		settingsChannelsIgnoreReactionAdd: string;
		settingsChannelsIgnoreAll: string;
		settingsDisabledchannels: string;
		settingsEventsBanadd: string;
		settingsEventsBanremove: string;
		settingsEventsMemberadd: string;
		settingsEventsMembernameupdate: string;
		settingsEventsMemberremove: string;
		settingsEventsMessagedelete: string;
		settingsEventsMessageedit: string;
		settingsEventsTwemojiReactions: string;
		settingsMessagesFarewell: string;
		settingsMessagesGreeting: string;
		settingsMessagesIgnorechannels: string;
		settingsMessagesJoinDm: string;
		settingsMessagesModerationAutoDelete: string;
		settingsMessagesModerationDm: string;
		settingsMessagesModerationMessageDisplay: string;
		settingsMessagesModerationReasonDisplay: string;
		settingsMessagesModeratorNameDisplay: string;
		settingsMessagesWarnings: string;
		settingsMessagesAnnouncementEmbed: string;
		settingsMusicAllowStreams: string;
		settingsMusicDefaultVolume: string;
		settingsMusicMaximumDuration: string;
		settingsMusicMaximumEntriesPerUser: string;
		settingsRolesAdmin: string;
		settingsRolesDj: string;
		settingsRolesInitial: string;
		settingsRolesModerator: string;
		settingsRolesMuted: string;
		settingsRolesPublic: string;
		settingsRolesRemoveinitial: string;
		settingsRolesRestrictedAttachment: string;
		settingsRolesRestrictedEmbed: string;
		settingsRolesRestrictedEmoji: string;
		settingsRolesRestrictedReaction: string;
		settingsRolesRestrictedVoice: string;
		settingsSelfmodAttachment: string;
		settingsSelfmodAttachmentmaximum: string;
		settingsSelfmodCapitalsEnabled: string;
		settingsSelfmodCapitalsIgnoredchannels: string;
		settingsSelfmodCapitalsIgnoredroles: string;
		settingsSelfmodCapitalsMaximum: string;
		settingsSelfmodCapitalsMinimum: string;
		settingsSelfmodFilterEnabled: string;
		settingsSelfmodFilterIgnoredchannels: string;
		settingsSelfmodFilterIgnoredroles: string;
		settingsSelfmodIgnorechannels: string;
		settingsSelfmodInvitesEnabled: string;
		settingsSelfmodInvitesIgnoredchannels: string;
		settingsSelfmodInvitesIgnoredroles: string;
		settingsSelfmodInvitesIgnoredcodes: string;
		settingsSelfmodInvitesIgnoredguilds: string;
		settingsSelfmodLinksEnabled: string;
		settingsSelfmodLinksIgnoredchannels: string;
		settingsSelfmodLinksIgnoredroles: string;
		settingsSelfmodLinksWhitelist: string;
		settingsSelfmodMessagesEnabled: string;
		settingsSelfmodMessagesIgnoredchannels: string;
		settingsSelfmodMessagesIgnoredroles: string;
		settingsSelfmodMessagesMaximum: string;
		settingsSelfmodMessagesQueueSize: string;
		settingsSelfmodNewlinesEnabled: string;
		settingsSelfmodNewlinesIgnoredchannels: string;
		settingsSelfmodNewlinesIgnoredroles: string;
		settingsSelfmodNewlinesMaximum: string;
		settingsSelfmodRaid: string;
		settingsSelfmodRaidthreshold: string;
		settingsSelfmodReactionsMaximum: string;
		settingsSelfmodReactionsBlacklist: string;
		settingsSelfmodReactionsEnabled: string;
		settingsSelfmodReactionsIgnoredchannels: string;
		settingsSelfmodReactionsIgnoredroles: string;
		settingsSelfmodReactionsWhitelist: string;
		settingsStarboardChannel: string;
		settingsStarboardIgnorechannels: string;
		settingsStarboardMinimum: string;
		settingsStarboardSelfstar: string;
		settingsRecruitmentEnabled: string;
		settingsRecruitmentChannel: string;
		settingsRecruitmentOfficerchannel: string;
		settingsRecruitmentOfficerrole: string;
		settingsRecruitmentViewerrole: string;
		settingsRecruitmentRecruitmessage: string;
		commandCreateMuteDescription: string;
		commandCreateMuteExtended: LanguageHelpDisplayOptions;
		commandCurrentTimeDescription: string;
		commandCurrentTimeExtended: LanguageHelpDisplayOptions;
		commandCurrentTimeLocationNotFound: string;
		commandCurrentTimeTitles: (params: {
			dst: string;
		}) => {
			currentTime: string;
			currentDate: string;
			country: string;
			gmsOffset: string;
			dst: string;
		};
		commandCurrentTimeDst: string;
		commandCurrentTimeNoDst: string;
		commandGsearchDescription: string;
		commandGsearchExtended: LanguageHelpDisplayOptions;
		commandGimageDescription: string;
		commandGimageExtended: LanguageHelpDisplayOptions;
		commandLmgtfyDescription: string;
		commandLmgtfyExtended: LanguageHelpDisplayOptions;
		commandLmgtfyClick: string;
		commandWeatherDescription: string;
		commandWeatherExtended: LanguageHelpDisplayOptions;
		googleErrorZeroResults: string;
		googleErrorRequestDenied: string;
		googleErrorInvalidRequest: string;
		googleErrorOverQueryLimit: string;
		googleErrorUnknown: string;
		commandNickDescription: string;
		commandNickExtended: LanguageHelpDisplayOptions;
		commandPermissionNodesDescription: string;
		commandPermissionNodesExtended: LanguageHelpDisplayOptions;
		commandTriggersDescription: string;
		commandTriggersExtended: LanguageHelpDisplayOptions;
		commandManagecommandautodeleteDescription: string;
		commandManagecommandautodeleteExtended: LanguageHelpDisplayOptions;
		commandManageCommandChannelDescription: string;
		commandManageCommandChannelExtended: LanguageHelpDisplayOptions;
		commandManageReactionRolesDescription: string;
		commandManageReactionRolesExtended: LanguageHelpDisplayOptions;
		commandSetIgnoreChannelsDescription: string;
		commandSetIgnoreChannelsExtended: LanguageHelpDisplayOptions;
		commandSetImageLogsDescription: string;
		commandSetImageLogsExtended: LanguageHelpDisplayOptions;
		commandSetMemberLogsDescription: string;
		commandSetMemberLogsExtended: LanguageHelpDisplayOptions;
		commandSetMessageLogsDescription: string;
		commandSetMessageLogsExtended: LanguageHelpDisplayOptions;
		commandSetmodlogsDescription: string;
		commandSetmodlogsExtended: LanguageHelpDisplayOptions;
		commandSetprefixDescription: string;
		commandSetprefixExtended: LanguageHelpDisplayOptions;
		commandSetrolechannelDescription: string;
		commandSetrolechannelExtended: LanguageHelpDisplayOptions;
		commandSetrolemessageDescription: string;
		commandSetrolemessageExtended: LanguageHelpDisplayOptions;
		commandSetStarboardEmojiDescription: string;
		commandSetStarboardEmojiExtended: LanguageHelpDisplayOptions;
		commandRoleInfoDescription: string;
		commandRoleInfoExtended: LanguageHelpDisplayOptions;
		commandGuildInfoDescription: string;
		commandGuildInfoExtended: LanguageHelpDisplayOptions;
		commandStickyRolesDescription: string;
		commandStickyRolesExtended: LanguageHelpDisplayOptions;
		commandManageAttachmentsDescription: string;
		commandManageAttachmentsExtended: LanguageHelpDisplayOptions;
		commandCapitalsModeDescription: string;
		commandCapitalsModeExtended: LanguageHelpDisplayOptions;
		commandFilterDescription: string;
		commandFilterExtended: LanguageHelpDisplayOptions;
		commandFilterModeDescription: string;
		commandFilterModeExtended: LanguageHelpDisplayOptions;
		commandInviteModeDescription: string;
		commandInviteModeExtended: LanguageHelpDisplayOptions;
		commandLinkModeDescription: string;
		commandLinkModeExtended: LanguageHelpDisplayOptions;
		commandMessageModeDescription: string;
		commandMessageModeExtended: LanguageHelpDisplayOptions;
		commandNewlineModeDescription: string;
		commandNewlineModeExtended: LanguageHelpDisplayOptions;
		commandReactionModeDescription: string;
		commandReactionModeExtended: LanguageHelpDisplayOptions;
		commandCuddleDescription: string;
		commandCuddleExtended: LanguageHelpDisplayOptions;
		commandDeletthisDescription: string;
		commandDeletthisExtended: LanguageHelpDisplayOptions;
		commandFDescription: string;
		commandFExtended: LanguageHelpDisplayOptions;
		commandGoodnightDescription: string;
		commandGoodnightExtended: LanguageHelpDisplayOptions;
		commandGoofytimeDescription: string;
		commandGoofytimeExtended: LanguageHelpDisplayOptions;
		commandHugDescription: string;
		commandHugExtended: LanguageHelpDisplayOptions;
		commandIneedhealingDescription: string;
		commandIneedhealingExtended: LanguageHelpDisplayOptions;
		commandRandRedditDescription: string;
		commandRandRedditExtended: LanguageHelpDisplayOptions;
		commandChaseDescription: string;
		commandChaseExtended: LanguageHelpDisplayOptions;
		commandShindeiruDescription: string;
		commandShindeiruExtended: LanguageHelpDisplayOptions;
		commandPeepoloveDescription: string;
		commandPeepoloveExtended: LanguageHelpDisplayOptions;
		commandSlapDescription: string;
		commandSlapExtended: LanguageHelpDisplayOptions;
		commandSnipeDescription: string;
		commandSnipeExtended: LanguageHelpDisplayOptions;
		commandThesearchDescription: string;
		commandThesearchExtended: LanguageHelpDisplayOptions;
		commandTriggeredDescription: string;
		commandTriggeredExtended: LanguageHelpDisplayOptions;
		commandUpvoteDescription: string;
		commandUpvoteExtended: LanguageHelpDisplayOptions;

		commandSetNicknameDescription: string;
		commandSetNicknameExtended: LanguageHelpDisplayOptions;
		commandAddRoleDescription: string;
		commandAddRoleExtended: LanguageHelpDisplayOptions;
		commandRemoveroleDescription: string;
		commandRemoveroleExtended: LanguageHelpDisplayOptions;
		commandSlowmodeDescription: string;
		commandSlowmodeExtended: LanguageHelpDisplayOptions;
		commandBanDescription: string;
		commandBanExtended: LanguageHelpDisplayOptions;
		commandDehoistDescription: string;
		commandDehoistExtended: LanguageHelpDisplayOptions;
		commandKickDescription: string;
		commandKickExtended: LanguageHelpDisplayOptions;
		commandLockdownDescription: string;
		commandLockdownExtended: LanguageHelpDisplayOptions;
		commandMuteDescription: string;
		commandMuteExtended: LanguageHelpDisplayOptions;
		commandPruneDescription: string;
		commandPruneExtended: LanguageHelpDisplayOptions;
		commandReasonDescription: string;
		commandReasonExtended: LanguageHelpDisplayOptions;
		commandRestrictAttachmentDescription: string;
		commandRestrictAttachmentExtended: LanguageHelpDisplayOptions;
		commandRestrictEmbedDescription: string;
		commandRestrictEmbedExtended: LanguageHelpDisplayOptions;
		commandRestrictEmojiDescription: string;
		commandRestrictEmojiExtended: LanguageHelpDisplayOptions;
		commandRestrictReactionDescription: string;
		commandRestrictReactionExtended: LanguageHelpDisplayOptions;
		commandRestrictVoiceDescription: string;
		commandRestrictVoiceExtended: LanguageHelpDisplayOptions;
		commandSoftBanDescription: string;
		commandSoftBanExtended: LanguageHelpDisplayOptions;
		commandToggleModerationDmDescription: string;
		commandToggleModerationDmExtended: LanguageHelpDisplayOptions;
		commandUnbanDescription: string;
		commandUnbanExtended: LanguageHelpDisplayOptions;
		commandUnmuteDescription: string;
		commandUnmuteExtended: LanguageHelpDisplayOptions;
		commandUnrestrictAttachmentDescription: string;
		commandUnrestrictAttachmentExtended: LanguageHelpDisplayOptions;
		commandUnrestrictEmbedDescription: string;
		commandUnrestrictEmbedExtended: LanguageHelpDisplayOptions;
		commandUnrestrictEmojiDescription: string;
		commandUnrestrictEmojiExtended: LanguageHelpDisplayOptions;
		commandUnrestrictReactionDescription: string;
		commandUnrestrictReactionExtended: LanguageHelpDisplayOptions;
		commandUnrestrictVoiceDescription: string;
		commandUnrestrictVoiceExtended: LanguageHelpDisplayOptions;
		commandUnwarnDescription: string;
		commandUnwarnExtended: LanguageHelpDisplayOptions;
		commandVmuteDescription: string;
		commandVmuteExtended: LanguageHelpDisplayOptions;
		commandVoiceKickDescription: string;
		commandVoiceKickExtended: LanguageHelpDisplayOptions;
		commandVunmuteDescription: string;
		commandVunmuteExtended: LanguageHelpDisplayOptions;
		commandWarnDescription: string;
		commandWarnExtended: LanguageHelpDisplayOptions;
		commandStarDescription: string;
		commandStarExtended: LanguageHelpDisplayOptions;
		commandDmDescription: string;
		commandDmExtended: LanguageHelpDisplayOptions;
		commandEvalDescription: string;
		commandEvalExtended: LanguageHelpDisplayOptions;
		commandExecDescription: string;
		commandExecExtended: LanguageHelpDisplayOptions;
		commandSetAvatarDescription: string;
		commandSetAvatarExtended: LanguageHelpDisplayOptions;
		commandDonateDescription: string;
		commandDonateExtended: LanguageHelpDisplayOptions;
		commandEchoDescription: string;
		commandEchoExtended: LanguageHelpDisplayOptions;
		commandFeedbackDescription: string;
		commandFeedbackExtended: LanguageHelpDisplayOptions;
		commandStatsDescription: string;
		commandStatsExtended: LanguageHelpDisplayOptions;
		commandAvatarDescription: string;
		commandAvatarExtended: LanguageHelpDisplayOptions;
		commandColorDescription: string;
		commandColorExtended: LanguageHelpDisplayOptions;
		commandContentDescription: string;
		commandContentExtended: LanguageHelpDisplayOptions;
		commandEmojiDescription: string;
		commandEmojiExtended: LanguageHelpDisplayOptions;
		commandCountryDescription: string;
		commandCountryExtended: LanguageHelpDisplayOptions;
		commandCountryTitles: {
			OVERVIEW: string;
			LANGUAGES: string;
			OTHER: string;
		};
		commandCountryFields: {
			overview: {
				officialName: string;
				capital: string;
				population: string;
			};
			other: {
				demonym: string;
				area: string;
				currencies: string;
			};
		};
		commandEshopDescription: string;
		commandEshopExtended: LanguageHelpDisplayOptions;
		commandEshopNotInDatabase: string;
		commandEshopTitles: {
			price: string;
			availability: string;
			releaseDate: string;
			numberOfPlayers: string;
			platform: string;
			categories: string;
			noCategories: string;
			nsuid: 'NSUID';
			esrb: 'ESRB';
		};
		commandEshopPricePaid: (params: { price: number }) => string;
		commandEshopPriceFree: string;
		commandHoroscopeDescription: string;
		commandHoroscopeExtended: LanguageHelpDisplayOptions;
		commandHoroscopeInvalidSunsign: (params: { sign: string; maybe: string }) => string;
		commandHoroscopeTitles: (params: {
			sign: string;
			intensity: string;
			keywords: readonly string[];
			mood: string;
			rating: string;
		}) => {
			dailyHoroscope: string;
			metadataTitle: string;
			metadata: readonly string[];
		};
		commandIgdbDescription: string;
		commandIgdbExtended: LanguageHelpDisplayOptions;
		commandIgdbTitles: {
			userScore: string;
			ageRating: string;
			releaseDate: string;
			genres: string;
			developers: string;
			platform: string;
		};
		commandIgdbData: {
			noDevelopers: string;
			noPlatforms: string;
			noReleaseDate: string;
			noRating: string;
			noSummary: string;
			noAgeRatings: string;
			noGenres: string;
		};
		commandItunesDescription: string;
		commandItunesExtended: LanguageHelpDisplayOptions;
		commandItunesTitles: {
			artist: string;
			collection: string;
			collectionPrice: string;
			trackPrice: string;
			trackReleaseDate: string;
			numberOfTracksInCollection: string;
			primaryGenre: string;
			preview: string;
			previewLabel: string;
		};
		commandMoviesDescription: string;
		commandMoviesExtended: LanguageHelpDisplayOptions;
		commandMoviesTitles: {
			runtime: string;
			userScore: string;
			status: string;
			releaseDate: string;
			imdbPage: string;
			homePage: string;
			collection: string;
			genres: string;
		};
		commandMoviesData: {
			variableRuntime: string;
			movieInProduction: string;
			linkClickHere: string;
			none: string;
			notPartOfCollection: string;
			noGenres: string;
		};
		commandShowsDescription: string;
		commandShowsExtended: LanguageHelpDisplayOptions;
		commandShowsTitles: {
			episodeRuntime: string;
			userScore: string;
			status: string;
			firstAirDate: string;
			genres: string;
		};
		commandShowsData: {
			variableRuntime: string;
			unknownUserScore: string;
			noGenres: string;
		};
		commandPriceDescription: string;
		commandPriceExtended: LanguageHelpDisplayOptions;
		commandQuoteDescription: string;
		commandQuoteExtended: LanguageHelpDisplayOptions;
		commandRolesDescription: string;
		commandRolesExtended: LanguageHelpDisplayOptions;
		commandDuckDuckGoDescription: string;
		commandDuckDuckGoExtended: LanguageHelpDisplayOptions;
		commandPollDescription: string;
		commandPollExtended: LanguageHelpDisplayOptions;
		commandPollReactionLimit: string;
		commandVoteDescription: string;
		commandVoteExtended: LanguageHelpDisplayOptions;
		commandTopInvitesDescription: string;
		commandTopInvitesExtended: LanguageHelpDisplayOptions;
		commandTopInvitesNoInvites: string;
		commandTopInvitesTop10InvitesFor: (params: { guild: Guild }) => string;
		commandTopInvitesEmbedData: {
			channel: string;
			link: string;
			createdAt: string;
			createdAtUnknown: string;
			expiresIn: string;
			neverExpress: string;
			temporary: string;
			uses: string;
		};
		commandUrbanDescription: string;
		commandUrbanExtended: LanguageHelpDisplayOptions;
		commandWhoisDescription: string;
		commandWhoisExtended: LanguageHelpDisplayOptions;
		commandFollowageDescription: string;
		commandFollowageExtended: LanguageHelpDisplayOptions;
		commandTwitchDescription: string;
		commandTwitchExtended: LanguageHelpDisplayOptions;
		commandTwitchSubscriptionDescription: string;
		commandTwitchSubscriptionExtended: LanguageHelpDisplayOptions;
		commandWikipediaDescription: string;
		commandWikipediaExtended: LanguageHelpDisplayOptions;
		commandYoutubeDescription: string;
		commandYoutubeExtended: LanguageHelpDisplayOptions;
		commandSubscribeNoRole: string;
		commandSubscribeSuccess: (params: { role: string }) => string;
		commandUnsubscribeSuccess: (params: { role: string }) => string;
		commandSubscribeNoChannel: string;
		commandAnnouncement: (params: { role: string }) => string;
		commandAnnouncementSuccess: string;
		commandAnnouncementCancelled: string;
		commandAnnouncementPrompt: string;
		commandAnnouncementEmbedMentions: (params: { header: string }) => string;
		commandAnnouncementEmbedMentionsWithMentions: (params: { header: string; mentions: string }) => string;
		commandInviteDescription: string;
		commandInviteExtended: LanguageHelpDisplayOptions;
		commandInvitePermissionInviteText: string;
		commandInvitePermissionsDescription: string;
		commandInfoBody: string[];
		commandHelpData: (params: {
			titleDescription: string;
			usage: string;
			extendedHelp: string;
			footerName: string;
		}) => {
			title: string;
			usage: string;
			extended: string;
			footer: string;
		};
		commandYarnDescription: string;
		commandYarnExtended: LanguageHelpDisplayOptions;
		commandYarnNoPackage: string;
		commandYarnUnpublishedPackage: (params: { pkg: string }) => string;
		commandYarnPackageNotFound: (params: { pkg: string }) => string;
		commandYarnEmbedDescriptionAuthor: (params: { author: string }) => string;
		commandYarnEmbedDescriptionMaintainers: string;
		commandYarnEmbedDescriptionLatestVersion: (params: { latestVersionNumber: string }) => string;
		commandYarnEmbedDescriptionLicense: (params: { license: string }) => string;
		commandYarnEmbedDescriptionMainFile: (params: { mainFile: string }) => string;
		commandYarnEmbedDescriptionDateCreated: (params: { dateCreated: string }) => string;
		commandYarnEmbedDescriptionDateModified: (params: { dateModified: string }) => string;
		commandYarnEmbedDescriptionDeprecated: (params: { deprecated: string }) => string;
		commandYarnEmbedDescriptionDependenciesLabel: string;
		commandYarnEmbedDescriptionDependenciesNoDeps: string;
		commandYarnEmbedMoreText: string;
		commandNickSet: (params: { nickname: string }) => string;
		commandNickCleared: string;
		commandPermissionNodesHigher: string;
		commandPermissionNodesInvalidType: string;
		commandPermissionNodesAdd: string;
		commandPermissionNodesNodeNotExists: string;
		commandPermissionNodesCommandNotExists: string;
		commandPermissionNodesRemove: string;
		commandPermissionNodesReset: string;
		commandPermissionNodesShowName: (params: { name: string }) => string;
		commandPermissionNodesShowAllow: (params: { allow: string }) => string;
		commandPermissionNodesShowDeny: (params: { deny: string }) => string;
		commandTriggersNotype: string;
		commandTriggersNooutput: string;
		commandTriggersInvalidreaction: string;
		commandTriggersInvalidalias: string;
		commandTriggersRemoveNottaken: string;
		commandTriggersRemove: string;
		commandTriggersAddTaken: string;
		commandTriggersAdd: string;
		commandTriggersListEmpty: string;
		commandGuildInfoTitles: Record<string, string>;
		commandGuildInfoRoles: (params: { roles: string }) => string;
		commandGuildInfoNoroles: string;
		commandGuildInfoChannels: (params: { text: number; voice: number; categories: number; afkChannelText: string }) => string[];
		commandGuildInfoChannelsAfkChannelText: (params: { afkChannel: string; afkTime: number }) => string;
		commandGuildInfoMembers: (params: { count: string; owner: User }) => string[];
		commandGuildInfoOther: (params: {
			size: number;
			region: string;
			createdAt: number;
			verificationLevel: 'NONE' | 'LOW' | 'MEDIUM' | 'HIGH' | 'VERY_HIGH';
		}) => string[];
		commandRoleInfoTitles: Record<string, string>;
		commandRoleInfoData: (params: { role: Role; hoisted: string; mentionable: string }) => string[];
		commandRoleInfoAll: string;
		commandRoleInfoNoPermissions: string;
		commandFilterUndefinedWord: string;
		commandFilterAlreadyFiltered: string;
		commandFilterNotFiltered: string;
		commandFilterAdded: (params: { word: string }) => string;
		commandFilterRemoved: (params: { word: string }) => string;
		commandFilterReset: string;
		commandFilterShowEmpty: string;
		commandFilterShow: (params: { words: string }) => string;
		commandManageAttachmentsRequiredValue: string;
		commandManageAttachmentsInvalidAction: string;
		commandManageAttachmentsMaximum: (params: { value: number }) => string;
		commandManageAttachmentsExpire: (params: { value: number }) => string;
		commandManageAttachmentsDuration: (params: { value: number }) => string;
		commandManageAttachmentsAction: string;
		commandManageAttachmentsLogs: string;
		commandManageAttachmentsEnabled: string;
		commandManageAttachmentsDisabled: string;
		commandManageCommandAutoDeleteTextChannel: string;
		commandManageCommandAutoDeleteRequiredDuration: string;
		commandManageCommandAutoDeleteShowEmpty: string;
		commandManageCommandAutoDeleteShow: (params: { codeblock: string }) => string;
		commandManageCommandAutoDeleteAdd: (params: { channel: string; time: number }) => string;
		commandManageCommandAutoDeleteRemove: (params: { channel: string }) => string;
		commandManageCommandAutoDeleteRemoveNotset: (params: { channel: string }) => string;
		commandManageCommandAutoDeleteReset: string;
		commandManageCommandChannelTextChannel: string;
		commandManageCommandChannelRequiredCommand: string;
		commandManageCommandChannelShow: (params: { channel: string; commands: string }) => string;
		commandManageCommandChannelShowEmpty: string;
		commandManageCommandChannelAddAlreadyset: string;
		commandManageCommandChannelAdd: (params: { channel: string; command: string }) => string;
		commandManageCommandChannelRemoveNotset: (params: { channel: string }) => string;
		commandManageCommandChannelRemove: (params: { channel: string; command: string }) => string;
		commandManageCommandChannelResetEmpty: string;
		commandManageCommandChannelReset: (params: { channel: string }) => string;
		commandManageReactionRolesShowEmpty: string;
		commandManageReactionRolesAddPrompt: string;
		commandManageReactionRolesAddChannel: (params: { emoji: string; channel: string }) => string;
		commandManageReactionRolesAddMissing: string;
		commandManageReactionRolesAdd: (params: { emoji: string; url: string }) => string;
		commandManageReactionRolesRemoveNotExists: string;
		commandManageReactionRolesRemove: (params: { emoji: string; url: string }) => string;
		commandManageReactionRolesResetEmpty: string;
		commandManageReactionRolesReset: string;
		commandSetStarboardEmojiSet: (params: { emoji: string }) => string;
		configurationTextChannelRequired: string;
		configurationEquals: string;
		commandSetIgnoreChannelsSet: (params: { channel: string }) => string;
		commandSetIgnoreChannelsRemoved: (params: { channel: string }) => string;
		commandSetImageLogsSet: (params: { channel: string }) => string;
		commandSetMemberLogsSet: (params: { channel: string }) => string;
		commandSetMessageLogsSet: (params: { channel: string }) => string;
		commandSetModLogsSet: (params: { channel: string }) => string;
		commandSetPrefixSet: (params: { prefix: string }) => string;
		commandStickyRolesRequiredUser: string;
		commandStickyRolesRequiredRole: string;
		commandStickyRolesNotExists: (params: { user: string }) => string;
		commandStickyRolesReset: (params: { user: string }) => string;
		commandStickyRolesRemove: (params: { user: string }) => string;
		commandStickyRolesAddExists: (params: { user: string }) => string;
		commandStickyRolesAdd: (params: { user: string }) => string;
		commandStickyRolesShowEmpty: string;
		commandStickyRolesShowSingle: (params: { user: string; roles: string }) => string;
		commandRandRedditRequiredReddit: string;
		commandRandRedditInvalidArgument: string;
		commandRandRedditBanned: string;
		commandRandRedditFail: string;
		commandRandRedditAllNsfw: string;
		commandRandRedditAllNsfl: string;
		commandRandRedditMessage: (params: { title: string; author: string; url: string }) => string;
		commandRandRedditErrorPrivate: string;
		commandRandRedditErrorQuarantined: string;
		commandRandRedditErrorNotFound: string;
		commandRandRedditErrorBanned: string;
		commandRedditUserDescription: string;
		commandRedditUserExtended: LanguageHelpDisplayOptions;
		commandRedditUserComplexityLevels: string[];
		commandRedditUserInvalidUser: (params: { user: string }) => string;
		commandRedditUserQueryFailed: string;
		commandRedditUserTitles: {
			linkKarma: string;
			commentKarma: string;
			totalComments: string;
			totalSubmissions: string;
			commentControversiality: string;
			textComplexity: string;
			top5Subreddits: string;
			bySubmissions: string;
			byComments: string;
			bestComment: string;
			worstComment: string;
		};
		commandRedditUserData: (params: {
			user: string;
			timestamp: string;
		}) => {
			overviewFor: string;
			permalink: string;
			dataAvailableFor: string;
			joinedReddit: string;
		};
		commandShipDescription: string;
		commandShipExtended: LanguageHelpDisplayOptions;
		commandShipData: (params: {
			romeoUsername: string;
			julietUsername: string;
			shipName: string;
		}) => {
			title: string;
			description: string;
		};
		commandSnipeEmpty: string;
		commandSnipeTitle: string;
		commandUpvoteMessage: string;
		commandVaporwaveDescription: string;
		commandVaporwaveExtended: LanguageHelpDisplayOptions;
		commandVaporwaveOutput: (params: { str: string }) => string;

		commandHistoryDescription: string;
		commandHistoryExtended: LanguageHelpDisplayOptions;
		commandHistoryFooterNew: (params: {
			warnings: number;
			mutes: number;
			kicks: number;
			bans: number;
			warningsText: string;
			mutesText: string;
			kicksText: string;
			bansText: string;
		}) => string;
		commandHistoryFooterWarning: (params: { count: number }) => string;
		commandHistoryFooterWarningPlural: (params: { count: number }) => string;
		commandHistoryFooterMutes: (params: { count: number }) => string;
		commandHistoryFooterMutesPlural: (params: { count: number }) => string;
		commandHistoryFooterKicks: (params: { count: number }) => string;
		commandHistoryFooterKicksPlural: (params: { count: number }) => string;
		commandHistoryFooterBans: (params: { count: number }) => string;
		commandHistoryFooterBansPlural: (params: { count: number }) => string;
		commandModerationsDescription: string;
		commandModerationsExtended: LanguageHelpDisplayOptions;
		commandModerationsEmpty: string;
		commandModerationsAmount: (params: { count: number }) => string;
		commandModerationsAmountPlural: (params: { count: number }) => string;
		commandMutesDescription: string;
		commandMutesExtended: LanguageHelpDisplayOptions;
		commandWarningsDescription: string;
		commandWarningsExtended: LanguageHelpDisplayOptions;

		commandPermissions: (params: { username: string; id: string }) => string;
		commandPermissionsAll: string;
		commandRaidDisabled: string;
		commandRaidMissingKick: string;
		commandRaidList: string;
		commandRaidClear: string;
		commandRaidCool: string;
		commandFlow: (params: { amount: number }) => string;
		commandTimeTimed: string;
		commandTimeUndefinedTime: string;
		commandTimeUnsupportedTipe: string;
		commandTimeNotScheduled: string;
		commandTimeAborted: (params: { title: string }) => string;
		commandTimeScheduled: (params: { title: string; user: User; time: number }) => string;
		commandSlowmodeSet: (params: { cooldown: number }) => string;
		commandSlowmodeReset: string;
		commandSlowmodeTooLong: string;
		commandBanNotBannable: string;
		commandDehoistStarting: (params: { count: number }) => string;
		commandDehoistProgress: (params: { count: number; percentage: number }) => string;
		commandDehoistEmbed: (params: {
			users: number;
			dehoistedMemberCount: number;
			dehoistedWithErrorsCount: number;
			errored: number;
		}) => {
			title: string;
			descriptionNoone: string;
			descriptionWithError: string;
			descriptionWithMultipleErrors: string;
			description: string;
			descriptionMultipleMembers: string;
			fieldErrorTitle: string;
		};
		commandKickNotKickable: string;
		commandLockdownLock: (params: { channel: string }) => string;
		commandLockdownLocking: (params: { channel: string }) => string;
		commandLockdownLocked: (params: { channel: string }) => string;
		commandLockdownUnlocked: (params: { channel: string }) => string;
		commandLockdownOpen: (params: { channel: string }) => string;
		commandMuteLowlevel: string;
		commandMuteConfigureCancelled: string;
		commandMuteConfigure: string;
		commandMuteConfigureToomanyRoles: string;
		commandMuteMuted: string;
		commandMuteUserNotMuted: string;
		commandMuteUnconfigured: string;
		commandMutecreateMissingPermission: string;
		commandRestrictLowlevel: string;
		commandPruneInvalid: string;
		commandPruneAlert: (params: { count: number; total: number }) => string;
		commandPruneAlertPlural: (params: { count: number; total: number }) => string;
		commandPruneInvalidPosition: string;
		commandPruneInvalidFilter: string;
		commandPruneNoDeletes: string;
		commandPruneLogHeader: string;
		commandPruneLogMessage: (params: { channel: string; author: string; count: number }) => string;
		commandPruneLogMessagePlural: (params: { channel: string; author: string; count: number }) => string;
		commandReasonMissingCase: string;
		commandReasonNotExists: string;
		commandReasonUpdated: (params: { entries: readonly number[]; newReason: string; count: number }) => string[];
		commandReasonUpdatedPlural: (params: { entries: readonly number[]; newReason: string; count: number }) => string[];
		commandToggleModerationDmToggledEnabled: string;
		commandToggleModerationDmToggledDisabled: string;
		commandUnbanMissingPermission: string;
		commandUnmuteMissingPermission: string;
		commandVmuteMissingPermission: string;
		commandVmuteUserNotMuted: string;
		commandWarnDm: (params: { moderator: string; guild: string; reason: string }) => string;
		commandWarnMessage: (params: { user: User; log: number }) => string;
		commandModerationOutput: (params: { count: number; range: string | number; users: string; reason: string | null }) => string;
		commandModerationOutputPlural: (params: { count: number; range: string | number; users: string; reason: string | null }) => string;
		commandModerationOutputWithReason: (params: { count: number; range: string | number; users: string; reason: string | null }) => string;
		commandModerationOutputWithReasonPlural: (params: { count: number; range: string | number; users: string; reason: string | null }) => string;
		commandModerationFailed: (params: { users: string; count: number }) => string;
		commandModerationFailedPlural: (params: { users: string; count: number }) => string;
		commandModerationDmFooter: string;
		commandModerationDmDescription: (params: { guild: string; title: string; reason: string | null; duration: number | null }) => string[];
		commandModerationDmDescriptionWithReason: (params: {
			guild: string;
			title: string;
			reason: string | null;
			duration: number | null;
		}) => string[];
		commandModerationDmDescriptionWithDuration: (params: {
			guild: string;
			title: string;
			reason: string | null;
			duration: number | null;
		}) => string[];
		commandModerationDmDescriptionWithReasonWithDuration: (params: {
			guild: string;
			title: string;
			reason: string | null;
			duration: number | null;
		}) => string[];
		commandModerationDays: string;
		commandRemindmeDescription: string;
		commandRemindmeExtended: LanguageHelpDisplayOptions;
		commandRemindmeCreate: (params: { id: string }) => string;
		commandRemindmeCreateNoDuration: string;
		commandRemindmeCreateNoDescription: string;
		commandRemindmeDeleteNoId: string;
		commandRemindmeDelete: (params: { task: ScheduleEntity; id: number }) => string;
		commandRemindmeListEmpty: string;
		commandRemindmeShowFooter: (params: { id: number }) => string;
		commandRemindmeInvalidId: string;
		commandRemindmeNotfound: string;
		commandSetColor: (params: { color: string }) => string;
		commandStarNostars: string;
		commandStarStats: string;
		commandStarStatsDescription: (params: { messages: string; stars: string }) => string;
		commandStarMessages: (params: { count: number }) => string;
		commandStarMessagesPlural: (params: { count: number }) => string;
		commandStars: (params: { count: number }) => string;
		commandStarsPlural: (params: { count: number }) => string;
		commandStarTopstarred: string;
		commandStarTopstarredDescription: (params: { medal: string; id: string; count: number }) => string;
		commandStarTopstarredDescriptionPlural: (params: { medal: string; id: string; count: number }) => string;
		commandStarTopreceivers: string;
		commandStarTopreceiversDescription: (params: { medal: string; id: string; count: number }) => string;
		commandStarTopreceiversDescriptionPlural: (params: { medal: string; id: string; count: number }) => string;
		commandEvalTimeout: (params: { seconds: number }) => string;
		commandEvalError: (params: { time: string; output: string; type: string }) => string;
		commandStatsTitles: {
			stats: string;
			uptime: string;
			serverUsage: string;
		};
		commandStatsFields: (params: {
			stats: StatsGeneral;
			uptime: StatsUptime;
			usage: StatsUsage;
		}) => {
			stats: string[];
			uptime: string[];
			serverUsage: string[];
		};
		commandTagDescription: string;
		commandTagExtended: LanguageHelpDisplayOptions;
		commandTagPermissionlevel: string;
		commandTagNameNotAllowed: string;
		commandTagNameTooLong: string;
		commandTagListEmpty: string;
		commandTagContentRequired: string;
		commandTagExists: (params: { tag: string }) => string;
		commandTagAdded: (params: { name: string; content: string }) => string;
		commandTagRemoved: (params: { name: string }) => string;
		commandTagNotexists: (params: { tag: string }) => string;
		commandTagEdited: (params: { name: string; content: string }) => string;
		commandTagReset: string;
		commandAvatarNone: string;
		commandColor: (params: { hex: string; rgb: string; hsl: string }) => string[];
		commandEmojiCustom: (params: { emoji: string; id: string }) => string[];
		commandEmojiTwemoji: (params: { emoji: string; id: string }) => string[];
		commandEmojiInvalid: string;
		commandEmojiTooLarge: (params: { emoji: string }) => string;
		commandEmotesDescription: string;
		commandEmotesExtended: LanguageHelpDisplayOptions;
		commandEmotesTitle: string;
		commandPriceCurrency: (params: { fromCurrency: string; fromAmount: number; worths: string[] }) => string;
		commandPriceCurrencyNotFound: string;
		commandQuoteMessage: string;
		commandRolesListEmpty: string;
		commandRolesAbort: (params: { prefix: string }) => string;
		commandRolesListTitle: string;
		commandRolesAdded: (params: { roles: string }) => string;
		commandRolesRemoved: (params: { roles: string }) => string;
		commandRolesNotPublic: (params: { roles: string }) => string;
		commandRolesNotManageable: (params: { roles: string }) => string;
		commandRolesAuditlog: string;
		commandDuckDuckGoNotfound: string;
		commandDuckDuckGoLookalso: string;
		commandUrbanNotFound: string;
		commandUrbanIndexNotfound: string;
		systemTextTruncated: (params: { definition: string; url: string }) => string;
		commandWhoisMemberTitles: {
			joined: string;
			createdAt: string;
		};
		commandWhoisMemberFields: (params: {
			member: GuildMember;
		}) => {
			joinedUnknown: string;
			joinedWithTimestamp: string;
			createdAt: string;
			footer: string;
		};
		commandWhoisMemberRoles: (params: { count: number }) => string;
		commandWhoisMemberRolesPlural: (params: { count: number }) => string;
		commandWhoisMemberPermissions: string;
		commandWhoisMemberPermissionsAll: string;
		commandWhoisUserTitles: {
			createdAt: string;
		};
		commandWhoisUserFields: (params: {
			user: User;
		}) => {
			createdAt: string;
			footer: string;
		};
		recruitmentQuestion1: (params: { member: GuildMember }) => string;
		recruitmentQuestion2: string;
		recruitmentQuestion3: string;
		recruitmentQuestion4: string;
		recruitmentQuestion5: string;
		recruitmentQuestion6: string;
		recruitmentQuestion7: string;
		recruitmentQuestion8: string;
		recruitmentQuestion9: string;
		recruitmentQuestion10: string;
		recruitmentQuestion11: string;
		constMonitorInvitelink: string;
		constMonitorLink: string;
		constMonitorWordfilter: string;
		constMonitorCapsfilter: string;
		constMonitorAttachmentfilter: string;
		constMonitorReactionfilter: string;
		moderationMonitorAttachments: string;
		moderationMonitorAttachmentsWithMaximum: (params: { amount: number; maximum: number }) => string;
		moderationMonitorCapitals: string;
		moderationMonitorCapitalsWithMaximum: (params: { amount: number; maximum: number }) => string;
		moderationMonitorInvites: string;
		moderationMonitorInvitesWithMaximum: (params: { amount: number; maximum: number }) => string;
		moderationMonitorLinks: string;
		moderationMonitorLinksWithMaximum: (params: { amount: number; maximum: number }) => string;
		moderationMonitorMessages: string;
		moderationMonitorMessagesWithMaximum: (params: { amount: number; maximum: number }) => string;
		moderationMonitorNewlines: string;
		moderationMonitorNewlinesWithMaximum: (params: { amount: number; maximum: number }) => string;
		moderationMonitorWords: string;
		moderationMonitorWordsWithMaximum: (params: { amount: number; maximum: number }) => string;
		monitorInviteFilterAlert: (params: { user: string }) => string;
		monitorInviteFilterLog: (params: { links: readonly string[]; count: number }) => string;
		monitorInviteFilterLogPlural: (params: { links: readonly string[]; count: number }) => string;
		monitorNolink: (params: { user: string }) => string;
		monitorWordFilterDm: (params: { filtered: string }) => string;
		monitorCapsFilterDm: (params: { message: string }) => string;
		monitorWordFilter: (params: { user: string }) => string;
		monitorCapsFilter: (params: { user: string }) => string;
		monitorMessageFilter: (params: { user: string }) => string;
		monitorNewlineFilter: (params: { user: string }) => string;
		monitorReactionsFilter: (params: { user: string }) => string;
		monitorSocialAchievement: string;
		inhibitorSpam: (params: { channel: string }) => string;
		hgBloodbath: readonly string[];
		hgDay: readonly string[];
		hgNight: readonly string[];
		serializerAutoRoleInvalid: string;
		serializerCommandAutoDeleteInvalid: string;
		serializerCustomCommandInvalid: string;
		serializerDisabledCommandChannelInvalid: string;
		serializerPermissionNodeDuplicatedCommand: (params: { command: string }) => string;
		serializerPermissionNodeInvalidCommand: (params: { command: string }) => string;
		serializerPermissionNodeInvalidTarget: string;
		serializerPermissionNodeInvalid: string;
		serializerPermissionNodeSecurityEveryoneAllows: string;
		serializerPermissionNodeSecurityGuarded: (params: { command: string }) => string;
		serializerPermissionNodeSecurityOwner: string;
		serializerReactionRoleInvalid: string;
		serializerStickyRoleInvalid: string;
		serializerTriggerAliasInvalid: string;
		serializerTriggerIncludeInvalid: string;
		serializerTwitchSubscriptionInvalidStreamer: string;
		serializerTwitchSubscriptionInvalid: string;
		serializerUniqueRoleSetInvalid: string;
		selfModerationCommandInvalidMissingAction: (params: { name: string }) => string;
		selfModerationCommandInvalidMissingArguments: (params: { name: string }) => string;
		selfModerationCommandInvalidSoftaction: (params: { name: string }) => string;
		selfModerationCommandInvalidHardaction: (params: { name: string }) => string;
		selfModerationCommandEnabled: string;
		selfModerationCommandDisabled: string;
		selfModerationCommandSoftAction: string;
		selfModerationCommandSoftActionWithValue: (params: { value: string }) => string;
		selfModerationCommandHardAction: (params: { value: string }) => string;
		selfModerationCommandHardActionDuration: string;
		selfModerationCommandHardActionDurationWithValue: (params: { value: number }) => string;
		selfModerationCommandThresholdMaximum: string;
		selfModerationCommandThresholdMaximumWithValue: (params: { value: number }) => string;
		selfModerationCommandThresholdDuration: string;
		selfModerationCommandThresholdDurationWithValue: (params: { value: number }) => string;
		selfModerationCommandShow: (params: {
			kEnabled: string;
			kAlert: string;
			kLog: string;
			kDelete: string;
			kHardAction: string;
			hardActionDurationText: string;
			thresholdMaximumText: string | number;
			thresholdDurationText: string;
		}) => readonly string[];
		selfModerationCommandShowDurationPermanent: string;
		selfModerationCommandShowUnset: string;
		selfModerationSoftActionAlert: string;
		selfModerationSoftActionLog: string;
		selfModerationSoftActionDelete: string;
		selfModerationHardActionBan: string;
		selfModerationHardActionKick: string;
		selfModerationHardActionMute: string;
		selfModerationHardActionSoftban: string;
		selfModerationHardActionWarning: string;
		selfModerationHardActionNone: string;
		selfModerationEnabled: string;
		selfModerationDisabled: string;
		selfModerationMaximumTooShort: (params: { minimum: number; value: number }) => string;
		selfModerationMaximumTooLong: (params: { maximum: number; value: number }) => string;
		selfModerationDurationTooShort: (params: { minimum: number; value: number }) => string;
		selfModerationDurationTooLong: (params: { maximum: number; value: number }) => string;
		moderationActions: ModerationAction;
		actionApplyReason: (params: { action: string; reason: string }) => string;
		actionApplyNoReason: (params: { action: string }) => string;
		actionRevokeReason: (params: { action: string; reason: string }) => string;
		actionRevokeNoReason: (params: { action: string }) => string;
		actionSoftbanReason: (params: { reason: string }) => string;
		actionUnSoftbanReason: (params: { reason: string }) => string;
		actionSoftbanNoReason: string;
		actionUnSoftbanNoReason: string;
		actionSetNicknameSet: (params: { reason: string }) => string;
		actionSetNicknameRemoved: (params: { reason: string }) => string;
		actionSetNicknameNoReasonSet: string;
		actionSetNicknameNoReasonRemoved: string;
		actionSetupMuteExists: string;
		actionSetupRestrictionExists: string;
		actionSetupTooManyRoles: string;
		actionSharedRoleSetupExisting: string;
		actionSharedRoleSetupExistingName: string;
		actionSharedRoleSetupNew: string;
		actionSharedRoleSetupAsk: (params: { role: string; channels: number; permissions: string }) => string;
		actionSharedRoleSetupAskMultipleChannels: (params: { role: string; channels: number; permissions: string }) => string;
		actionSharedRoleSetupAskMultiplePermissions: (params: { role: string; channels: number; permissions: string }) => string;
		actionSharedRoleSetupAskMultipleChannelsMultiplePermissions: (params: { role: string; channels: number; permissions: string }) => string;
		actionRequiredMember: string;
		muteNotConfigured: string;
		restrictionNotConfigured: string;
		muteNotInMember: string;
		muteLowHierarchy: string;
		muteCannotManageRoles: string;
		muteNotExists: string;
		resolverDateSuffix: string;
		resolverPositiveAmount: string;
		systemPoweredByWeebsh: string;
		prefixReminder: (params: { prefix: string }) => string;
		unexpectedIssue: string;
		commandDmNotSent: string;
		commandDmSent: string;
		commandRoleHigherBot: string;
		commandRoleHigher: string;
		commandSuccess: string;
		commandToBot: string;
		commandUserself: string;
		systemParseError: string;
		systemHighestRole: string;
		systemChannelNotPostable: string;
		systemFetchbansFail: string;
		systemLoading: readonly string[];
		systemError: string;
		systemDatabaseError: string;
		systemDiscordAborterror: string;
		systemQueryFail: string;
		systemNoResults: string;
		systemMessageNotFound: string;
		systemNotenoughParameters: string;
		systemCannotAccessChannel: string;
		systemExceededLengthOutput: (params: { output: string; time?: string; type?: string }) => string;
		systemExceededLengthOutputWithTypeAndTime: (params: { output: string; time?: string; type?: string }) => string;
		systemExceededLengthOutputConsole: (params: { time?: string; type?: string }) => string;
		systemExceededLengthOutputConsoleWithTypeAndTime: (params: { time?: string; type?: string }) => string;
		systemExceededLengthOutputFile: (params: { time?: string; type?: string }) => string;
		systemExceededLengthOutputFileWithTypeAndTime: (params: { time?: string; type?: string }) => string;
		systemExceededLengthOutputHastebin: (params: { url: string; time?: string; type?: string }) => string;
		systemExceededLengthOutputHastebinWithTypeAndTime: (params: { url: string; time?: string; type?: string }) => string;
		systemExceededLengthChooseOutput: (params: { output: string[] }) => string;
		systemExternalServerError: string;
		systemPokedexExternalResource: string;
		jumpTo: string;
		resolverInvalidChannelName: (params: { name: string }) => string;
		resolverChannelNotInGuild: string;
		resolverChannelNotInGuildSubcommand: (params: { command: string; subcommand: string }) => string;
		resolverInvalidRoleName: (params: { name: string }) => string;
		resolverInvalidUsername: (params: { name: string }) => string;
		resolverMembernameUserLeftDuringPrompt: string;
		listifyPage: (params: { page: number; pageCount: number; results: string }) => string;
		moderationLogAppealed: string;
		moderationLogExpiresIn: (params: { duration: number }) => string;
		moderationLogDescription: (params: { data: Moderation.ModerationManagerDescriptionData }) => string;
		moderationLogFooter: (params: { caseID: number }) => string;
		moderationCaseNotExists: string;
		moderationCasesNotExist: string;
		guildSettingsChannelsMod: string;
		guildSettingsRolesRestricted: (params: { prefix: string; path: string }) => string;
		guildMuteNotFound: string;
		guildBansEmpty: string;
		guildBansNotFound: string;
		channelNotReadable: string;
		userNotInGuild: string;
		userNotExistent: string;
		eventsGuildMemberAdd: string;
		eventsGuildMemberAddMute: string;
		eventsGuildMemberAddRaid: string;
		eventsGuildMemberAddDescription: (params: { mention: string; time: number }) => string;
		eventsGuildMemberRemove: string;
		eventsGuildMemberKicked: string;
		eventsGuildMemberBanned: string;
		eventsGuildMemberSoftBanned: string;
		eventsGuildMemberRemoveDescription: (params: { mention: string; time: number }) => string;
		eventsGuildMemberRemoveDescriptionWithJoinedAt: (params: { mention: string; time: number }) => string;
		eventsGuildMemberUpdateNickname: (params: { previous: string; current: string }) => string;
		eventsGuildMemberAddedNickname: (params: { previous: string; current: string }) => string;
		eventsGuildMemberRemovedNickname: (params: { previous: string }) => string;
		eventsNicknameUpdate: string;
		eventsUsernameUpdate: string;
		eventsNameUpdatePreviousWasSet: (params: { previousName: string | null }) => string;
		eventsNameUpdatePreviousWasNotSet: (params: { previousName: string | null }) => string;
		eventsNameUpdateNextWasSet: (params: { nextName: string | null }) => string;
		eventsNameUpdateNextWasNotSet: (params: { nextName: string | null }) => string;
		eventsGuildMemberNoUpdate: string;
		eventsGuildMemberAddedRoles: (params: { addedRoles: string }) => string;
		eventsGuildMemberAddedRolesPlural: (params: { addedRoles: string }) => string;
		eventsGuildMemberRemovedRoles: (params: { removedRoles: string }) => string;
		eventsGuildMemberRemovedRolesPlural: (params: { removedRoles: string }) => string;
		eventsRoleUpdate: string;
		eventsMessageUpdate: string;
		eventsMessageDelete: string;
		eventsReaction: string;
		eventsCommand: (params: { command: string }) => string;
		settingsDeleteChannelsDefault: string;
		settingsDeleteRolesInitial: string;
		settingsDeleteRolesMute: string;
		modlogTimed: (params: { remaining: number }) => string;
		guildWarnNotFound: string;
		guildMemberNotVoicechannel: string;
		promptlistMultipleChoice: (params: { list: string; count: number }) => string;
		promptlistMultipleChoicePlural: (params: { list: string; count: number }) => string;
		promptlistAttemptFailed: (params: { list: string; attempt: number; maxAttempts: number }) => string;
		promptlistAborted: string;
		fuzzySearchMatches: (params: { matches: number; codeblock: string }) => string;
		fuzzySearchAborted: string;
		fuzzySearchInvalidNumber: string;
		fuzzySearchInvalidIndex: string;
		eventsErrorWtf: string;
		eventsErrorString: (params: { mention: string; message: string }) => string;
		constUsers: string;
		constMonitorMessagefilter: string;
		constMonitorNewlinefilter: string;
		unknownChannel: string;
		unknownRole: string;
		unknownUser: string;
		notificationsTwitchNoGameName: string;
		notificationsTwitchEmbedDescription: (params: { userName: string }) => string;
		notificationsTwitchEmbedDescriptionWithGame: (params: { userName: string; gameName: string }) => string;
		notificationTwitchEmbedFooter: string;
	}
}
